packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  better-auth: 1.3.4
  eslint: ^9.32.0
  next: ^15.3.5
  prettier: ^3.6.2
  typescript: ^5.9.2
  zod: 4.0.15
  "@tanstack/react-query": ^5.80.7
  "@trpc/client": ^11.4.0
  "@trpc/tanstack-react-query": ^11.4.0
  "@trpc/server": ^11.4.0
catalogs:
  react19:
    '@types/react': ^19.1.6
    '@types/react-dom': ^19.1.5
    react: 19.1.0
    react-dom: 19.1.0

onlyBuiltDependencies:
  - esbuild
