packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@orpc/client': ^1.8.0
  '@orpc/server': ^1.8.0
  '@orpc/tanstack-query': ^1.8.0
  better-auth: 1.3.4
  eslint: ^9.32.0
  next: ^15.3.5
  prettier: ^3.6.2
  typescript: ^5.9.2
  zod: 4.0.15

catalogs:
  react19:
    '@types/react': ^19.1.6
    '@types/react-dom': ^19.1.5
    react: 19.1.0
    react-dom: 19.1.0

onlyBuiltDependencies:
  - esbuild
