packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.20.1
  next: ^15.3.5
  prettier: ^3.6.2
  typescript: ^5.8.3
  zod: 3.25.76

catalogs:
  react19:
    '@types/react': ^19.1.6
    '@types/react-dom': ^19.1.5
    react: 19.0.0
    react-dom: 19.0.0

onlyBuiltDependencies:
  - esbuild
