import type { Metadata } from "next";
import { cookies, headers } from "next/headers";
import Navbar from "@/components/layout/navbar";
import { auth } from "@/lib/auth/server";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
  robots: { index: false, follow: false },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  // Get session server-side
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  return (
    <div className="relative flex-1">
      <Navbar session={session} />
      {children}
    </div>
  );
}
