import type { Metadata } from "next";
import { cookies } from "next/headers";

import { SidebarInset, SidebarProvider } from "@ziron/ui/sidebar";

import Navbar from "@/components/layout/navbar";
import { AppSidebar } from "@/components/layout/sidebar/app-sidebar";
import { getSession } from "@/lib/auth/server";
import { ExistingMediaDialog } from "@/modules/media/components/existing-media-dialog";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
  robots: { index: false, follow: false },
};

/**
 * Server component that renders the dashboard layout with sidebar, navbar, and content area.
 *
 * Retrieves the sidebar open state from cookies and the user session server-side, then provides these to layout components.
 *
 * @param children - The content to display within the dashboard layout
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  // Get session server-side
  const session = await getSession();

  return (
    <SidebarProvider
      defaultOpen={defaultOpen}
      style={
        {
          "--sidebar-width": "calc(var(--spacing) * 52)",
          "--header-height": "calc(var(--spacing) * 12)",
        } as React.CSSProperties
      }
    >
      <AppSidebar session={session} variant="sidebar" />
      <SidebarInset>
        <div className="relative flex-1">
          <Navbar session={session} />
          {children}
        </div>
      </SidebarInset>
      <ExistingMediaDialog />
    </SidebarProvider>
  );
}
