import type { Metadata } from "next";
import "@ziron/ui/globals.css";

import { Navbar } from "@/components/layout/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {/* <Banner inset>
        <BannerIcon icon={<IconExpandDiagonalDuo className="size-4" />} />
        <BannerTitle>Important message</BannerTitle>
        <BannerAction>Learn more</BannerAction>
        <BannerClose />
      </Banner> */}
      <Navbar />
      {children}
    </>
  );
}
