import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "@ziron/ui/globals.css";

import { cn } from "@ziron/utils";

import { Providers } from "@/components/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased", geistSans.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
